### ISSUE TITLE
Ever-decreasing length

### ISSUE THREAD

**Issue by andrewKyres** [luanpotter/ordered_set#1]
Sometimes, an item is not removed but the exposed length decreases regardless.

**Comment by andrewKyres** [comment]
If this happens for an item-test pair once, then it will continue to happen for that pair on future removeWhere() calls.

**Comment by luanpotter** [comment]
can you provide a complete example of the problem, with the expected result and the actual results?

**Comment by andrewKyres** [comment]
I've narrowed it down to:
```
int removeWhere(bool Function(E element) test) {
    final prevLength = _length;
    for (final es in _backingSet.toList()) {
      final removed = es.where(test).length;
      if (removed == es.length) {
        print('$removed ${_backingSet.lookup(es)}');
        print(es);
        print(_backingSet);
        _backingSet.remove(es);
      } else {
        es.removeWhere(test);
      }
      _length -= removed;
    }
    return prevLength - _length;
  }
```

prints:

```
1 null
[Instance of 'A']
{[Instance of 'B'], [Instance of 'D'], [Instance of 'C'], [Instance of 'A'], [Instance of 'F'], [Instance of 'D'], [Instance of 'E'], [Instance of 'C']}
```

Would es not be found if the state of the instance of A changes?

Edit: Sorry I can't get pretty whitespace

**Comment by andrewKyres** [comment]
Oh, I just realized you're the author of Flame! So it's the game loop calling `components.removeWhere((c) => c.destroy());`, if that makes any difference.

**Comment by andrewKyres** [comment]
Oh ok so the issue is probably that my component's priority was y.round(), so once it moved it was no longer found. I think it's reasonable to want to render components based on y values, so should I open an issue in Flame instead?

**Comment by luanpotter** [comment]
@andrewKyres I edited your message to be formatted.

you didn't provide the actual code you ran to get the output, just the `removeWhere` code and the output. I mean the code that creates sets and call `removeWhere` and it doesn't work.

I am the author of Flame haha. I made this lib to support flame.

Anyway, the crux of your issue, I think, is, and I'm not sure I properly documented this, but the `priority` must never change at runtime. Because the ordered_set will not be updated.

Do you need the order in which the components are rendered to be changed after the components are created?

**Comment by andrewKyres** [comment]
> Do you need the order in which the components are rendered to be changed after the components are created?

I do! I want 2d orthographic so characters lower on screen should be rendered after higher ones such that they are on top. 

I imagine updating the ordered set constantly would be too costly and I know that rendering will happen once per loop. So, I’m likely looking for some heap-like structure where everything will be appended until render time, at which point it’ll be reordered in O(n).

**Comment by luanpotter** [comment]
That would work, another thing I have in mind is to expose a `resort` api that you must manually call, in your case, whenever characters move in the y axis (which I imagine is a lot but not every tick). That is a very interesting problem, so I think we have two things to do:

(1) open an issue/pr here because we need to better document the fact that you can't change priorities at runtime (it was in my head at the time and I thought I had written docs about it but I couldn't find it now so probably I didn't)

(2) open an issue on flame so we can discuss what is the better way to support this requirement of changing priorities

**Comment by luanpotter** [comment]
`resort` sounded weird, but I meant `re-sort` haha
